name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel libssl-dev libffi-dev libsqlite3-dev zlib1g-dev
        pip install --upgrade pip
        pip install buildozer

    - name: Initialize Buildozer
      run: |
        cd ${{ github.workspace }}
        buildozer init

    - name: Copy main.py to match Buildozer spec
      run: |
        cp main.py main.py.bak  # backup
        echo '[app]\ntitle = Pinterest Downloader\npackage.name = pinterestdownloader\npackage.domain = org.example\nsource.dir = .\nsource.include_exts = py,png,jpg,kv,atlas\nversion = 1.0\nrequirements = python3,kivy,requests,beautifulsoup4\norientation = portrait\nosx.python_version = 3\n[buildozer]\nlog_level = 2\nwarn_on_root = 0' > buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pinterest-downloader-apk
        path: bin/*.apk
