name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Use stable Ubuntu version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential zip unzip openjdk-17-jdk python3-pip python3-setuptools libssl-dev libffi-dev libsqlite3-dev zlib1g-dev git

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer

    - name: Initialize Buildozer
      run: buildozer init

    - name: Inject buildozer.spec
      run: |
        echo '[app]
title = Pinterest Downloader
package.name = pinterestdownloader
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy,requests,beautifulsoup4
orientation = portrait
osx.python_version = 3

[buildozer]
log_level = 2
warn_on_root = 0
' > buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: pinterest-downloader-apk
        path: bin/*.apk
